import Foundation

/// Real Claude Code 2.1.280 screens captured on 2026-09-28 with the exact probe
/// command (`--safe-mode --ax-screen-reader ... /usage`), PTY bytes unchanged
/// except for a private working-folder path replaced with a neutral one.
enum ClaudeUsageScreenFixtures {
    /// The CLI without a subscription sign-in (captured where it could not reach
    /// the keychain) shows the session cost panel instead of subscription limits.
    static let apiBilling = "[Screen Reader Mode: on via flag]\r\n\u{1B}7\u{1B}[r\u{1B}8\u{1B}[?25h\u{1B}[?2004h\u{1B}[?2031h\u{1B}[?1004h\u{1B}[>0q\u{1B}[?u\u{1B}[c\u{1B}[GClaude Code v2.1.280\r\nOpus 5.5 (1M context) · API Usage Billing\r\n~/Library/Application Support/Weekleft/QuotaProbe\r\nwarning: Safe mode: all customizations are disabled (CLAUDE.md, skills, plugins, hooks, MCP, agents, and more)\r\nRestart without --safe-mode to re-enable\r\nyou: /usage\r\nSettings  Status   Config   Usage   Stats\r\nSession\r\nTotal cost:            $0.0000\r\nTotal duration (API):  0s\r\nTotal duration (wall): 0s\r\nTotal code changes:    0 lines added, 0 lines removed\r\nUsage:                 0 input, 0 output, 0 cache read, 0 cache write\r\nEsc to cancel\u{1B}[29G\u{1B}[7A"
    /// The owner's own Terminal on 2026-09-28 08:33 (keychain available, signed in,
    /// Max plan in Claude Desktop): the CLI still reports API Usage Billing, so
    /// `/usage` has no subscription limits to read. This, not a new screen layout,
    /// is why 0.2.4 showed "response format not supported" (audit r2 R2-L-01).
    /// The home folder is replaced with a neutral one.
    static let apiBillingInTerminal = "[Screen Reader Mode: on via flag]\r\n\u{1B}7\u{1B}[r\u{1B}8\u{1B}[?25h\u{1B}[?2004h\u{1B}[?2031h\u{1B}[?1004h\u{1B}]0;✳ Claude Code\u{7}\u{1B}]0;◐ Claude Code\u{7}\u{1B}]0;✳ Claude Code\u{7}\u{1B}[>0q\u{1B}[?u\u{1B}[c\u{1B}[GClaude Code v2.1.280\r\nOpus 5.5 (1M context) · API Usage Billing\r\n/Users/user\r\nwarning: Safe mode: all customizations are\r\ndisabled (CLAUDE.md, skills, plugins, hooks,\r\nMCP, agents, and more)\r\nRestart without --safe-mode to re-enable\r\nUsing Opus 5.5 (1M context) (from\r\n.claude/settings.json) · /model\r\nyou: /usage\r\nSettings  Status   Config   Usage   Stats\r\nSession\r\nTotal cost:            $0.0000\r\nTotal duration (API):  0s\r\nTotal duration (wall): 0s\r\nTotal code changes:    0 lines added, 0 lines\r\nremoved\r\nUsage:                 0 input, 0 output, 0\r\ncache read, 0 cache write\r\nEsc to cancel\u{1B}[29G\u{1B}[9A"
    /// First launch in a folder that Claude Code does not trust yet.
    static let untrustedFolder = "[Screen Reader Mode: on via flag]\r\n\u{1B}7\u{1B}[r\u{1B}8\u{1B}[?25h\u{1B}[?2004h\u{1B}[?2031h\u{1B}[?1004h\u{1B}[>0q\u{1B}[?u\u{1B}[c\u{1B}[GPermission Required: Accessing workspace:\r\n/Users/example/Library/Application Support/Weekleft/QuotaProbe\r\nQuick safety check: Is this a project you created or one you trust? (Like your own code, a well-known open source project, or work from your team). If not, take\r\n a moment to review what's in this folder first.\r\nClaude Code'll be able to read, edit, and execute files here.\r\nSecurity guide\r\ny. Yes, I trust this folder\r\nn. No, exit\r\nEnter y/n:\r\nEnter to confirm · Esc to cancel\u{1B}[12G\u{1B}[1A"
    /// The owner's signed-in Claude Code 2.1.283 on a Max plan, 2026-09-28 10:32
    /// Europe/Vienna, with the exact probe command: the session and weekly windows,
    /// a separate weekly Fable window, the new "What's contributing" breakdown and
    /// Usage credits. Home folder and skill names replaced with neutral ones.
    static let subscription: String? = "[Screen Reader Mode: on via flag]\r\n\u{1B}7\u{1B}[r\u{1B}8\u{1B}[?25h\u{1B}[?2004h\u{1B}[?2031h\u{1B}[?1004h\u{1B}]0;✳ Claude Code\u{7}\u{1B}]0;◐ Claude Code\u{7}\u{1B}]0;✳ Claude Code\u{7}\u{1B}[>0q\u{1B}[?u\u{1B}[c\u{1B}[GClaude Code v2.1.283\r\nOpus 5.5 (1M context) · Claude Max\r\n/Users/user\r\nwarning: Safe mode: all customizations are disabled (CLAUDE.md, skills, plugins,\r\n hooks, MCP, agents, and more)\r\nRestart without --safe-mode to re-enable\r\nUsing Opus 5.5 (1M context) (from .claude/settings.json) · /model\r\nyou: /usage\r\nSettings  Status   Config   Usage   Stats\r\nSession\r\nTotal cost:            $0.0000\r\nTotal duration (API):  0s\r\nTotal duration (wall): 0s\r\nTotal code changes:    0 lines added, 0 lines removed\r\nUsage:                 0 input, 0 output, 0 cache read, 0 cache write\r\nCurrent session\r\n2% 2% used\r\nResets 2:59pm (Europe/Vienna)\r\nCurrent week (all models)\r\n27% 27% used\r\nResets Oct 4 at 11:59pm (Europe/Vienna)\r\nCurrent week (Fable)\r\n16% 16% used\r\nResets Oct 4 at 11:59pm (Europe/Vienna)\r\nWhat's contributing to your limits usage?\r\nApproximate, based on local sessions on this machine — does not include other\r\ndevices or claude.ai\r\nLast 24h · these are independent characteristics of your usage, not a breakdown\r\n100% of your usage came from subagent-heavy sessions\r\nEach subagent runs its own requests. Be deliberate about spawning them — and\r\nconsider configuring a cheaper model for simpler subagents.\r\n92% of your usage was at >150k context\r\nLonger sessions are more expensive even when cached. /compact mid-task, /clear\r\nwhen switching to new tasks.\r\n87% of your usage came from sessions active for 8+ hours\r\nThese are often background/loop sessions. Continuous usage can add up quickly so\r\n make sure it is intentional.\r\n72% of your usage came from subagents under \"general-purpose\"\r\nIf this runs frequently, consider configuring its subagents with a cheaper model\r\n or tightening their prompts.\r\nSkills % of usage\r\n/anthropic-skills:example-writing-skill 1%\r\nSubagents % of usage\r\ngeneral-purpose 72%\r\nanthropic-skills:example-writing-skill 7%\r\nPlugins % of usage\r\nanthropic-skills 7%\r\nMCP servers % of usage\r\ncomputer-use 1%\r\nd to day · w to week\r\nUsage credits\r\nUsage credits are off · /usage-credits to turn them on\r\nEsc to cancel\u{1B}[29G\u{1B}[44A"
    /// When `subscription` was captured: resets on the screen are read relative to it.
    static let subscriptionCapturedAt: Date? = ISO8601DateFormatter().date(from: "2026-09-28T08:32:30Z")
}
